### ISSUE TITLE
Match and Pattern compilation checklist

### ISSUE THREAD

**Issue by dafaust** [Rust-GCC/gccrs#1479]
This is a brain dump of the various bits of match expressions that we
aren't currently compiling. Probably incomplete.

Patterns https://doc.rust-lang.org/reference/patterns.html
- [x] Literal Patterns `1`, `'a'`
- [ ] Identifier Patterns and bindings `e @ 1..=5`
- [x] Wildcard Patterns `_`
- [ ] Rest Patterns `..`
- [x] Range Patterns `1..=5`
- [ ] Reference Patterns
- [x] Struct Patterns
- [x] TupleStruct Patterns
- [ ] Tuple Patterns
     Done? at least in match expressions
- [ ] Grouped Patterns `&(0..=5)`
- [x] Path Patterns
- [ ] Or-patterns `Foo::A | Foo::B`
- [ ] Slice Patterns `[a, b, _]`

Match to-dos (done items not listed)
- [ ] path-to-tuple scrutinee  #1478 is one fix)
- [ ] struct scrutinee (i.e. non-enum ADT)
- [ ] nested tuple scrutinee `match ((Foo::A, 1), ('c', Foo::B))`
- [ ] match arm guards `Some(x) if x < 10`

**Comment by powerboat9** [comment]
Superseded by #2082, can probably be closed @philberty
