### ISSUE TITLE
Tracking issue for experimental features in 1.49 implemented in gccrs

### ISSUE THREAD

**Issue by MajoraSans** [Rust-GCC/gccrs#3210]
- [ ] abi_avr_interrupt (https://github.com/rust-lang/rust/issues/69664)
- [ ] abi_msp430_interrupt (https://github.com/rust-lang/rust/issues/38487)
- [ ] abi_ptx (https://github.com/rust-lang/rust/issues/38788)
- [ ] abi_x86_interrupt (https://github.com/rust-lang/rust/issues/40180)
- [ ] alloc_error_handler (https://github.com/rust-lang/rust/issues/51540)
- [ ] arbitrary_self_types (https://github.com/rust-lang/rust/issues/44874)
- [ ] associated_type_defaults (https://github.com/rust-lang/rust/issues/29661)
- [ ] async_closure (https://github.com/rust-lang/rust/issues/62290)
- [ ] auto_traits (https://github.com/rust-lang/rust/issues/13231)
- [ ] box_patterns (https://github.com/rust-lang/rust/issues/29641)
- [ ] c_variadic (https://github.com/rust-lang/rust/issues/44930)
- [ ] cfg_sanitize (https://github.com/rust-lang/rust/issues/39699)
- [ ] cfg_target_thread_local (https://github.com/rust-lang/rust/issues/29594)
- [ ] cfg_version (https://github.com/rust-lang/rust/issues/64796)
- [ ] cmse_nonsecure_entry (https://github.com/rust-lang/rust/issues/75835)
- [ ] const_extern_fn (https://github.com/rust-lang/rust/issues/64926)
- [ ] const_muts_ref (https://github.com/rust-lang/rust/issues/57349)
- [ ] const_precise_live_drops (https://github.com/rust-lang/rust/issues/73255)
- [ ] const_refs_to_cell (https://github.com/rust-lang/rust/issues/80384)
- [ ] const_trait_impl (https://github.com/rust-lang/rust/issues/67792)
- [ ] const_try (https://github.com/rust-lang/rust/issues/74935)
- [ ] coroutines (https://github.com/rust-lang/rust/issues/43122)
- [ ] custom_inner_attributes (https://github.com/rust-lang/rust/issues/54726)
- [ ] custom_test_frameworks (https://github.com/rust-lang/rust/issues/50297)
- [ ] decl_macro (https://github.com/rust-lang/rust/issues/39412)
- [ ] do_not_recommend (https://github.com/rust-lang/rust/issues/51992)
- [ ] doc_auto_cfg (https://github.com/rust-lang/rust/issues/43781)
- [ ] doc_cfg (https://github.com/rust-lang/rust/issues/43781)
- [ ] doc_cfg_hide (https://github.com/rust-lang/rust/issues/43781)
- [ ] doc_masked (https://github.com/rust-lang/rust/issues/44027)
- [ ] doc_notable_trait (https://github.com/rust-lang/rust/issues/45040)
- [ ] dropck_eyepatch ((https://github.com/rust-lang/rust/issues/34761)
- [ ] exhaustive_patterns (https://github.com/rust-lang/rust/issues/51085)
- [ ] extern_types (https://github.com/rust-lang/rust/issues/43467)
- [ ] ffi_const (https://github.com/rust-lang/rust/issues/58328)
- [ ] ffi_pure (https://github.com/rust-lang/rust/issues/58328)
- [ ] fundamental (https://github.com/rust-lang/rust/issues/29635)
- [ ] generic_const_exprs (https://github.com/rust-lang/rust/issues/76560)
- [ ] half_open_range_patterns_in_slices (https://github.com/rust-lang/rust/issues/67264)
- [ ] if_let_guard (https://github.com/rust-lang/rust/issues/51114)
- [ ] impl_trait_in_assoc_type (https://github.com/rust-lang/rust/issues/63063)
- [ ] inherent_associated_types (https://github.com/rust-lang/rust/issues/8995)
- [ ] inlline_const_pat (https://github.com/rust-lang/rust/issues/76001)
- [ ] lang_items (https://doc.rust-lang.org/unstable-book/language-features/lang-items.html)
- [ ] let_chains (https://github.com/rust-lang/rust/issues/53667)
- [ ] link_llvm_intrinsics (https://github.com/rust-lang/rust/issues/29602)
- [ ] linkage (https://github.com/rust-lang/rust/issues/29603)
- [ ] marker_trait_attr (https://github.com/rust-lang/rust/issues/29864)
- [ ] min_specialization (https://github.com/rust-lang/rust/issues/31844)
- [ ] more_qualified_paths (https://doc.rust-lang.org/unstable-book/language-features/more-qualified-paths.html)
- [ ] needs_panic_runtime (https://github.com/rust-lang/rust/issues/32837)
- [ ] negative_impls (https://github.com/rust-lang/rust/issues/68318)
- [ ] never_type (https://github.com/rust-lang/rust/issues/35121)
- [ ] never_type_fallback (https://github.com/rust-lang/rust/issues/65992) 
- [ ] no_core (https://github.com/rust-lang/rust/issues/29639)
- [ ] no_sanitize (https://github.com/rust-lang/rust/issues/39699)
- [ ] object_safe_for_dispatch (https://github.com/rust-lang/rust/issues/43561)
- [ ] optimize_attribute (https://github.com/rust-lang/rust/issues/54882)
- [ ] panic_runtime (https://github.com/rust-lang/rust/issues/32837)
- [ ] postfix_match (https://doc.rust-lang.org/unstable-book/language-features/postfix-match.html)
- [ ] proc_macro_hygiene (https://github.com/rust-lang/rust/issues/54727)
- [ ] profiler_runtime (https://github.com/rust-lang/rust/issues/42524)
- [ ] register_tool (https://github.com/rust-lang/rust/issues/66079)
- [ ] repr_simd (https://github.com/rust-lang/rust/issues/27731)
- [ ] repr128 (https://github.com/rust-lang/rust/issues/56071)
- [ ] rustc_allow_const_fn_unstable (https://github.com/rust-lang/rust/issues/69399)
- [ ] rustc_private (https://github.com/rust-lang/rust/issues/27812)
- [ ] simd_ffi (https://github.com/rust-lang/rust/issues/27731)
- [ ] specialization (https://github.com/rust-lang/rust/issues/31844)
- [ ] start (https://github.com/rust-lang/rust/issues/29633)
- [ ] stmt_expr_attributes (https://github.com/rust-lang/rust/issues/15701)
- [ ] structural_match (https://github.com/rust-lang/rust/issues/31434)
- [ ] target_feature_11 (https://github.com/rust-lang/rust/issues/69098)
- [ ] thread_local (https://github.com/rust-lang/rust/issues/29594)
- [ ] trait_alias (https://github.com/rust-lang/rust/issues/41517)
- [ ] trait_upcasting (https://github.com/rust-lang/rust/issues/65991)
- [ ] transparent_unions (https://github.com/rust-lang/rust/issues/60405)
- [ ] trivial_bounds (https://github.com/rust-lang/rust/issues/48214)
- [ ] try_blicks (https://github.com/rust-lang/rust/issues/31436)
- [ ] type_alias_impl_trait (https://github.com/rust-lang/rust/issues/63063)
- [ ] unboxed_closures (https://github.com/rust-lang/rust/issues/63063)
- [ ] unnamed_fields (https://github.com/rust-lang/rust/issues/49804)
- [ ] unsized_fn_params (https://github.com/rust-lang/rust/issues/48055)
- [ ] unsized_locals (https://github.com/rust-lang/rust/issues/48055)
- [ ] unsized_tuple_coercion (https://github.com/rust-lang/rust/issues/42877)
