### ISSUE TITLE
Handle repetition separators properly

### ISSUE THREAD

**Issue by CohenArthur** [Rust-GCC/gccrs#947]
When repeating tokens using `?+*`, one can add separators to the invocation, i.e:
```rust
macro_rules! repeat {
    ($($any:literal),*) => { ... }
}
```
will match the following: `repeat!(1), repeat!(1, 2, 3), repeat!(1  , 2      , 46)`

- [x] Handle separators properly once repetitions are implemented
- [x] Restrict separators on some fragments
    - [x] `expr` and `stmt` may only be followed by one of: `=>`, `,`, or `;`. #1044 
    - [x] `pat` and `pat_param` may only be followed by one of: `=>`, `,`, `=`, `|`, `if`, or `in`. #1051 
    - [x] `path` and `ty` may only be followed by one of: `=>`, `,`, `=`, `|`, `;`, `:`, `>`, `>>`, `[`, `{`, `as`, `where`, or a macro variable of block fragment specifier. #1051 
    - [x] `vis` may only be followed by one of: `,`, an identifier other than a non-raw priv, any token that can begin a type, or a metavariable with a `ident`, `ty`, or `path` fragment specifier. #1051 

```rust
error: `$a:expr` is followed by `sep`, which is not allowed for `expr` fragments
 --> gcc/testsuite/rust/compile/xfail/macro8.rs:2:16
  |
2 |     ($($a:expr)sep*) => {
  |                ^^^ not allowed after `expr` fragments
  |
  = note: allowed there are: `=>`, `,` or `;`

error: aborting due to previous error
```

From https://doc.rust-lang.org/reference/macros-by-example.html#follow-set-ambiguity-restrictions

- [ ] #1055 

If a repetition can occur zero times, then the set of follow-up restrictions must also be checked for the match arriving afterwards:
```rust
macro_rules! add_with_reserved_kw {
    ($a:expr $(,)? tok) => {{}};
}
```
errors out with
```rust
error: `$a:expr` may be followed by `tok`, which is not allowed for `expr` fragments
 --> test.rs:2:20
  |
2 |     ($a:expr $(,)? tok) => {{}};
  |                    ^^^ not allowed after `expr` fragments
  |
  = note: allowed there are: `=>`, `,` or `;`
```
